openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /:
    get:
      responses:
        "200":
          description: OK
components:
  schemas:
    BudgetCategoryDTO:
      description: "Budget category. A null name means a new uncategorized budget."
      required:
        - userId
        - name
      properties:
        id:
          type: string
        userId:
          type: string
        name:
          type: string
        subcategories:
          type: array
          items:
            $ref: "#/components/schemas/BudgetCategoryDTO"
        budgets:
          type: array
          items:
            $ref: "#/components/schemas/BudgetDTO"
    BudgetDTO:
      required:
        - name
        - investment
        - userId
      properties:
        id:
          type: string
        name:
          type: string
        budgetEntries:
          type: array
          items:
            $ref: "#/components/schemas/EntryDTO"
        investment:
          type: boolean
        userId:
          type: string
    EntryDTO:
      required:
        - value
        - currency
        - name
        - userId
      properties:
        id:
          type: string
        value:
          type: number
        currency:
          $ref: "#/components/schemas/EntryCurrency"
        name:
          type: string
        entryType:
          $ref: "#/components/schemas/EntryType"
        userId:
          type: string
        budgetId:
          type: string
        date:
          type: string
          format: date
          example: "2022-01-01"
    EntryCurrency:
      type: string
      enum:
        - PLN
        - EUR
        - CHF
    EntryType:
      type: string
      default: expense
      enum:
        - income
        - expense
    UserDTO:
      required:
        - userId
      properties:
        userId:
          type: string
        password:
          type: string

