openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8980/analysis'
paths:
  /monthly/sum/{startDate}/{endDate}/{budgetId}:
    get:
      operationId: getExpenseBalanceByPeriodAndId
      description: "Get expense/income balance for a given month and budget."
      parameters:
        - name: startDate
          in: path
          description: "Start date of the period to be analyzed."
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: path
          description: "End date of the period to be analyzed."
          required: true
          schema:
            type: string
            format: date
        - name: budgetId
          in: path
          description: "Id of the given budget."
          required: true
          schema:
            type: string
      tags:
        - budget-analysis
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: number