openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8980/{userId}/budgets' # todo https?
    variables:
      userId:
        default: "demo"
        description: "Id of the currently logged user."
paths:
  /categories:
    get:
      operationId: getUserCategories
      description: "Get categories for given user."
      tags:
        - budget
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BudgetCategoryDTO"
  /addCategory:
    post:
      operationId: addCategory
      description: "Add a new budget category."
      tags:
        - budget
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BudgetCategoryDTO"
      responses:
        "200":
          description: OK
  /budgetFavorites:
    get:
      operationId: recentBudgetList
      description: "Get list of recent budget names."
      tags:
        - budget
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /add:
    post:
      operationId: addBudget
      description: "Add a new budget to category or a new top-level budget."
      tags:
        - budget
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BudgetCategoryDTO"
      responses:
        "200":
          description: OK
  /categories/delete/{name}:
    delete:
      operationId: deleteCategory
      description: "Delete budget category with a given name."
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      tags:
        - budget
      responses:
        "200":
          description: OK
  /delete/{name}:
    delete:
      operationId: deleteBudget
      description: "Delete budget with a given name."
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      tags:
        - budget
      responses:
        "200":
          description: OK


components:
  schemas:
    BudgetCategoryDTO:
      description: "Budget category. A null name means a new uncategorized budget."
      properties:
        name:
          type: string
        subcategories:
          type: array
          items:
            $ref: "#/components/schemas/BudgetCategoryDTO"
        budgets:
          type: array
          items:
            $ref: "#/components/schemas/BudgetDTO"
    BudgetDTO:
      required:
        - name
        - isInvestment
      properties:
        id:
          type: string
        name:
          type: string
        entryCategories:
          type: array
          items:
            $ref: "./EntrySchema.yaml#/components/schemas/EntryCategoryDTO"
        uncategorizedEntries:
          type: array
          items:
            $ref: "./EntrySchema.yaml#/components/schemas/EntryDTO"
        isInvestment:
          type: boolean
    UserDTO:
      properties:
        userId:
          type: string
        password:
          type: string
        budgets:
          type: array
          items:
            $ref: "#/components/schemas/BudgetDTO"
