openapi: 3.0.3
info:
  title: Entry schema
  description: Schema containing API specification related to entries.
  version: 1.0.0
servers:
  - url: 'http://localhost:8980/entry' # todo https?

paths:
  /{userId}/add:
    post:
      operationId: addEntry
      description: "Add a new entry to the budget."
      parameters:
        - name: userId
          in: path
          description: "Id of the currently logged user."
          required: true
          schema:
            type: string
      tags:
        - entry
      requestBody:
        content:
          application/json:
            schema:
              $ref:
                '#/components/schemas/EntryDTO'
      responses:
        "200":
          description: OK
          # TODO maybe send back the added entry here?
  /{userId}/delete/{id}:
    delete:
      operationId: deleteEntry
      description: "Delete entry with a given id."
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: path
          name: userId
          description: "Id of the currently logged user."
          required: true
          schema:
            type: string
      tags:
        - entry
      responses:
        "200":
          description: OK

components:
  schemas:
    EntryDTO:
      required:
        - value
        - currency
        - name
        - budgetName
      properties:
        id:
          type: string
        value:
          type: number
        currency:
         $ref: "#/components/schemas/Currency"
        name:
          type: string
        entryType:
          $ref: "#/components/schemas/EntryType"
        budgetName:
         type: string
        date:
          type: string
          format: date
          example: "01-01-2022"
    Currency:
      type: string
      enum:
        - PLN
        - EUR
        - CHF
    EntryType:
      type: string
      default: expense
      enum:
        - income
        - expense

