openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8980/investments/analysis'

paths:
  /profits/{date}/{budgetId}:
    get:
      operationId: getProfitByDateAndId
      description: "Get profit for given date and budget."
      parameters:
        - name: date
          in: path
          description: "Date for which profit should be calculated."
          required: true
          schema:
            type: string
            format: date
        - name: budgetId
          in: path
          description: "Id of the given budget."
          required: true
          schema:
            type: string
        - name: excludePurchasesFrom
          in: query
          description: "Any units bought after this date will be excluded from profit analysis."
          required: false
          schema:
            type: string
            format: date
      tags:
        - investment-analysis
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: number


#  /investments/profits/category/{budgetCategoryId}:
#    get:
#      operationId: getProfitByDateAndId
#      description: "Get profit for a given date and budget."
#      parameters:
#        - name: date
#          in: path
#          description: "Date for which the profit should be calculated."
#          required: true
#          schema:
#            type: string
#            format: date
#        - name: budgetId
#          in: path
#          description: "Id of the given budget."
#          required: true
#          schema:
#            type: string
#      tags:
#        - investment-analysis
#      responses:
#        "200":
#          description: OK
#          content:
#            application/json:
#              schema:
#                type: number
  
