openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8980/investments/analysis'

paths:
  /profits/{date}/{budgetId}:
    get:
      operationId: getProfitByDateAndId
      description: "Get profit for given date and budget."
      parameters:
        - name: date
          in: path
          description: "Date for which profit should be calculated."
          required: true
          schema:
            type: string
            format: date
        - name: budgetId
          in: path
          description: "Id of the given budget."
          required: true
          schema:
            type: string
        - name: excludePurchasesFrom
          in: query
          description: "Any units bought after this date will be excluded from profit analysis."
          required: false
          schema:
            type: string
            format: date
      tags:
        - investment-analysis
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: number
  /sum/marketValue/subcategories/{startDate}/{endDate}/{budgetCategoryId}:
    get:
      operationId: getTotalMarketValueForSubcategoriesAndPeriodByCategoryId
      description: "Get total invested sum for direct subcategories of a category with given id."
      parameters:
        - name: startDate
          in: path
          description: "Start date of the period to be analyzed."
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: path
          description: "End date of the period to be analyzed."
          required: true
          schema:
            type: string
            format: date
        - name: budgetCategoryId
          in: path
          description: "Id of the given budget category."
          required: true
          schema:
            type: string
      tags:
        - investment-analysis
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubcategoryMarketValueDTO'

#  /investments/profits/category/{budgetCategoryId}:
#    get:
#      operationId: getProfitByDateAndId
#      description: "Get profit for a given date and budget."
#      parameters:
#        - name: date
#          in: path
#          description: "Date for which the profit should be calculated."
#          required: true
#          schema:
#            type: string
#            format: date
#        - name: budgetId
#          in: path
#          description: "Id of the given budget."
#          required: true
#          schema:
#            type: string
#      tags:
#        - investment-analysis
#      responses:
#        "200":
#          description: OK
#          content:
#            application/json:
#              schema:
#                type: number

components:
  schemas:
    SubcategoryExpenseSumDTO:
      type: object
      required:
        - subcategoryName
        - expenseSum
      properties:
        subcategoryId:
          type: string
        subcategoryName:
          type: string
        expenseSum:
          type: number
    SubcategoryMarketValueDTO:
      type: object
      required:
        - subcategoryName
        - marketValue
      properties:
        subcategoryId:
          type: string
        subcategoryName:
          type: string
        marketValue:
          type: number
  
