openapi: 3.0.3
info:
  title: Main view
  description:  Main view
  version: 1.0.0
servers:
  - url: 'http://localhost:8980/main' # todo https?
paths:
  /addEntry:
    post:
      operationId: addEntry
      description: "Add entry to a budget"
      tags:
        - entry
      requestBody:
        content:
          application/json:
            schema:
              $ref:
                '#/components/schemas/EntryDTO'
      responses:
        "200":
          description: OK
          # TODO
  /{userId}/budgetFavorites:
    get:
      operationId: recentBudgetList
      description: "Get list of recent budget names"
      tags:
        - budget
      parameters:
        - name: userId # todo is this parameter necessary once authentication is in place?
          in: path
          description: "Username of the currently logged user"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

components:
  schemas:
    EntryDTO:
      properties:
        value:
          type: number
        currency:
          type: string
          enum: [PLN, EUR, CHF]
        name:
          type: string
        entryType:
          type: string
          enum:
            - income
            - expense
        budgetName:
         type: string
    BudgetDTO:
      properties:
        name:
          type: string
        budgetEntries:
          type: array
          items:
            $ref: "#/components/schemas/EntryDTO"
        isInvestment:
          type: boolean
    UserDTO:
      properties:
        userId:
          type: string
        password:
          type: string
        budgets:
          type: array
          items:
            $ref: "#/components/schemas/BudgetDTO"

