openapi: 3.0.3
info:
  title: User schema
  description: Schema with user-related operations.
  version: 1.0.0
servers:
  - url: 'http://localhost:8980/users' # todo https?
paths:
  /add:
    post:
      operationId: addUser
      description: "Add a new user account to the database"
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDTO"
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: OK
          content:
            text/plain:
              schema:
                type: string

  /get/username/{username}:
    post:
      operationId: getByUsername
      description: "Get user by username"
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
      tags:
        - user
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
  # todo update/delete

components:
  schemas:
    UserDTO:
      required:
        - username
      properties:
        username:
          type: string
        userId:
          type: string
        password:
          type: string
