version: '3.7'
services:
  mongodb:
    image: 'mongo:4.4.3'
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  mongo-express: # todo for development purposes, remove later
    image: mongo-express
    container_name: mongo_express_container
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_MONGODB_SERVER: mongodb_container

networks:
  default:
    name: mongodb_network

volumes:
  data: {}
